spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/tasknote?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: < username >
    password: < password >